interface TextKeys {
    HOMEPAGE: string
    PUBLIC_TIER_LISTS: string
    MY_ACCOUNT: string
    SETTINGS: string
    SUPPORT: string
    LOGOUT: string
    SEARCH_TIER_LISTS: string
    SEARCH: string
    TYPE_COMMAND_OR_SEARCH_TIER_LIST: string
    PROFILE: string
    NO_RESULT: string
    SUGGESTIONS: string
    CANCEL: string
    CONFIRM: string
    CONTINUE: string
    SLOGAN: string
    SLOGAN_HTML: string
    TIERLISTMAKER: string
    NEW_TIER_LISTS: string
    CREATE_A_TEMPLATE: string
    TIER_LIST_DEFINITION: string
    TIER_SORT_MOST_VOTED: string
    VIDEOS_GAMES_TEMPLATES: string
    RECENTLY_CREATED_TEMPLATES: string
    SPORTS_TEMPLATES: string
    MUSIC_TEMPLATES: string
    RANK_NOW: string
    CREATE_NEW_TEMPLATE: string
    CREATE_NEW_TEMPLATE_DESCRIPTION: string
    TEMPLATE_NAME: string
    TEMPLATE_NAME_EXAMPLE: string
    CATEGORY: string
    SELECT_CATEGORY: string
    CATEGORIES: string
    COVER_IMAGE: string
    SELECT_IMAGES_TEXT: string
    SELECT_IMAGES_TEXT_ADD: string
    CHOOSE_ALL_IMAGES_AT_ONCE: string
    USE_CONSISTENT_IMAGES: string
    MINIMUM_IMAGE_AMOUNT: string
    ROW_NAMES: string
    ADD_ROW: string
    REMOVE_ROW: string
    MINIMUM_ROW_AMOUNT_ERROR: string
    MAXIMUM_ROW_AMOUNT_ERROR: string
    OK: string
    ENTER_A_TEMPLATE_NAME: string
    TEMPLATE_NAME_TOO_SHORT: string
    TEMPLATE_NAME_TOO_LONG: string
    SELECT_A_CATEGORY: string
    SELECT_A_COVER_IMAGE: string
    COVER_IMAGE_TOO_LARGE: string
    TEMPLATE_IMAGES_TOO_LARGE: string
    NOT_ENOUGH_TEMPLATE_IMAGES: string
    TOO_MANY_TEMPLATE_IMAGES: string
    PLEASE_SELECT_TEMPLATE_IMAGES: string
    CREATE_TEMPLATE: string
    CREATE_CATEGORY_TEMPLATE: string
    TEMPLATE_DESCRIPTION: string
    TEMPLATE_DESCRIPTION_EXAMPLE: string
    ENTER_A_TEMPLATE_DESCRIPTION: string
    TEMPLATE_DESCRIPTION_TOO_SHORT: string
    TEMPLATE_DESCRIPTION_TOO_LONG: string
    ROW_NAME_TOO_LONG: string
    PUBLIC_TEMPLATE: string
    CREATING_TEMPLATE: string
    TEMPLATE_CREATED: string
    FAILED_TO_CREATE_TEMPLATE: string
    TIER_LIST: string
    CREATE_TIERLIST: string
    DOWNLOAD_IMAGE: string
    formatDate: (date: Date) => string
    UNVOTING_TIERLIST: string
    UNVOTING_TIERLIST_FAILED: string
    UNVOTED_TIERLIST: string
    VOTING_TIERLIST: string
    VOTING_TIERLIST_FAILED: string
    VOTED_TIERLIST: string
    UNDO: string
    TIER_LISTS: string
    API_REQUEST_FAILED: string
    NO_VOTED_TEMPLATES: string
    NO_SPORTS_TEMPLATES: string
    NO_VIDEO_GAMES_TEMPLATES: string
    LINK_GOOGLE_ACCOUNT: string
    LINK_GOOGLE_ACCOUNT_DESCRIPTION: string
    CONTINUE_WITH_GOOGLE: string
    BY_CONTINUING_YOU_AGREE_TO_OUR_TERMS: string
    FEATURE_IN_DEVELOPMENT: string
    NEED_TO_BE_SIGNED_IN_TO_VOTE: string
    SIGN_IN: string
    START_FOR_FREE: string
    GENERAL: string
    IMAGES: string
    TIERS: string
    EDIT_TEMPLATE: string
    EDIT_TEMPLATE_DESCRIPTION: string
    SAVE_CHANGES: string
    TEMPLATE_IMAGES: string
    CURRENT_TEMPLATE_IMAGES: string
    UPDATING_TIERLIST_INFORMATION: string
    TIERLIST_INFORMATION_UPDATED: string
    FAILED_TO_UPDATE_TIERLIST_INFORMATION: string
    TIERLIST_NOT_FOUND: string
    TEMPLATE_IMAGE_NAME_TOO_LONG: string
    TOO_MANY_IMAGES_IN_TEMPLATE: string
    UPDATING_COVER_IMAGE: string
    UPDATING_COVER_IMAGE_FAILED: string
    COVER_IMAGE_UPDATED: string
    DELETING_TEMPLATE_IMAGES: string
    DELETING_TEMPLATE_IMAGES_FAILED: string
    TEMPLATE_IMAGES_DELETED: string
    ADDING_TEMPLATE_IMAGES: string
    ADDING_TEMPLATE_IMAGES_FAILED: string
    TEMPLATE_IMAGES_ADDED: string
    UPDATING_TEMPLATE_ROWS: string
    TEMPLATE_ROWS_UPDATED: string
    FAILED_TO_UPDATE_TEMPLATE_ROWS: string
    GO_BACK: string
    MY_TIER_LIST_TEMPLATES: string
    EDIT: string

    DELETE: string
    PROFILE_DESCRIPTION: string
    NO_TEMPLATES_CREATED_YET: string
    DELETE_TEMPLATE: string
    DELETE_TEMPLATE_MESSAGE: string
    DELETING_TEMPLATE: string
    TEMPLATE_DELETED: string
    FAILED_TO_DELETE_TEMPLATE: string
    SHOW_IMAGE_NAMES: string
    UPLOAD_IMAGES: string
    IMAGE_NAME_INFO: string
    COOKIE_CONSENT_FORCE: string
    WE_USE_COOKIES: string
    WE_USE_COOKIE_DESCRIPTION: string
    BY_CLICKING_ACCEPT: string
    ACCEPT: string
    DECLINE: string
    SHARE_TEMPLATE: string
    SHARE_DIRECTLY: string
    SHARE_TIERLIST_TEXT: string
    DROP_IMAGE: string
    USER_RANKING_TITLE: string
    SHARE_YOUR_RANKING: string
    LINK_COPIED: string
    CLOSE: string
    RANK_YOURSELF: string
    GOOGLE_IMAGE_SEARCH: string
    LOADING_IMAGES_FOR: string
    NO_IMAGES_FOUND: string
    SUCCESSFULLY_LOADED_IMAGES: string
    ADD_IMAGES: string
    ADDING_IMAGES: string
    ADDED_IMAGES: string
    FAILED_TO_ADD_IMAGES: string
    GOOGLE_IMAGES: string
    SUPPORT_MESSAGE: string
    NO_TEMPLATES: string
    VIEW_TEMPLATES: string
    CATEGORIES_PAGE_DESCRIPTION: string
    TEMPLATES: string
    RESET_TIERLIST: string
    COPY_SUCCESSFUL: string
    SHOW_IMAGE_NAME_QUESTION: string
    RECENTLY_CREATED: string
    MOST_VOTED: string
    NEW: string
    CREATE_A_NEW_TEMPLATE: string
    CREATE_A_NEW_TEMPLATE_DESCRIPTION: string
    TEMPLATE_DESCRIPTION_SUBTITLE: string
    TEMPLATE_CATEGORY_SUBTITLE: string
    PUBLIC_OR_PRIVATE_SUBTITLE: string
    SELECT_A_COVER_IMAGE_SUBTITLE: string
    SELECT_A_SET_OF_IMAGES_SUBTITLE: string
    SELECT_IMAGES: string
    ENTER_ROW_NAMES_SUBTITLE: string
    SURE_TO_CREATE_TEMPLATE: string

    EDIT_GENERAL_INFORMATION_SUBTITLE: string
    EDIT_TEMPLATE_IMAGES_SUBTITLE: string
    EDIT_TEMPLATE_ROWS_SUBTITLE: string
    UPDATE_COVER_IMAGE: string
    COVER: string
    EDIT_TEMPLATE_COVER_SUBTITLE: string
    ADD: string

    PUBLIC: string
    PRIVATE: string


    SELECTION_CATEGORIES: {
        VIDEO_GAMES: string
        MOVIES: string
        BOOKS: string
        MUSIC: string
        TV_SHOWS: string
        SPORTS: string
        ANIME: string
        MEMES: string
        CELEBRITIES: string
        FOOD: string
        POLITICS: string
        SCIENCE: string
        HISTORY: string
        TECHNOLOGY: string
        FASHION: string
        TRAVEL: string
        FITNESS: string
        BUSINESS: string
        CULTURE: string
        RANDOM: string
    }
}

export default TextKeys;